version: "3"
services:
  ##########################
  #  APP SERVICE ENVIRONMENT
  ##########################
  app:
    build: .
    restart: always
    healthcheck:
      test: "env | grep SHELL_SESSION_ID"
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 15s
    ports:
      - 4000
    env_file: .env
    depends_on:
      - database
    volumes:
      - ./:/usr/share/app
      - /usr/share/app/node_modules
    networks:
      - node_networks
  ##############################
  # DATABASE SERVICE ENVIRONMENT
  ##############################
  database:
    image: postgres:14-alpine
    restart: always
    healthcheck:
      test: "env | grep SHELL_SESSION_ID"
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 15s
    env_file: .env
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DBNAME}
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql
    networks:
      - node_networks
  #############################
  # QUEUE SERVICE ENVIRONMENT
  #############################
  queue:
    restart: always
    image: rabbitmq:3-management-alpine
    healthcheck:
      test: "env | grep SHELL_SESSION_ID"
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 15s
    env_file:
      - .env
    environment:
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - queue:/var/lib/rabbitmq/data
    networks:
      - node_networks
# VOLUME PERSISTENT DATA
#############################
volumes:
  database:
  queue:
#############################
# NETWORKS SHARING GROUP
#############################
networks:
  node_networks: